name: Mirror SourceHut repos

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      GH_MIRROR_TOKEN: ${{ secrets.GH_MIRROR_TOKEN }}

    steps:
      - name: Checkout this repo (workflow + script)
        uses: actions/checkout@v4

      - name: Restore repo cache
        uses: actions/cache@v4
        with:
          path: repos
          key: mirror-${{ runner.os }}-${{ hashFiles('mirror.py') }}-${{ github.run_number }}
          restore-keys: |
            mirror-${{ runner.os }}-${{ hashFiles('mirror.py') }}-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run mirror script
        run: |
          python3 ./mirror.py

      - name: Generate badge JSON
        run: |
          ts="$(date -u +'%Y-%m-%d %H:%M UTC')"
          cat > last-mirror.json <<'EOF'
          {"schemaVersion":1,"label":"last mirror","message":"","color":"blue"}
          EOF
          # inject timestamp
          jq --arg msg "$ts" '.message=$msg' last-mirror.json > badge.json && mv badge.json last-mirror.json
     
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          destination_dir: badge
          keep_files: true
